apiVersion: v1
kind: Service
metadata:
  name: devops-buddy
spec:
  type: NodePort
  selector:
    app: devops-buddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      NodePort: 30777
